// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dependency struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

type Device struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Image *Image `json:"image"`
}

type Image struct {
	ID           string        `json:"id"`
	Repository   string        `json:"repository"`
	Tag          string        `json:"tag"`
	Dependencies []*Dependency `json:"dependencies"`
}

type Vulnerability struct {
	ID          string      `json:"id"`
	Description string      `json:"description"`
	Dependency  *Dependency `json:"dependency"`
}
